#!/bin/sh

# ۱. تنظیمات VLANها
uci -q delete network.vlan10; uci -q delete network.vlan20
uci set network.vlan10=device; uci set network.vlan10.type='8021q'; uci set network.vlan10.ifname='eth0'; uci set network.vlan10.vid='10'
uci set network.vlan20=device; uci set network.vlan20.type='8021q'; uci set network.vlan20.ifname='eth0'; uci set network.vlan20.vid='20'

# ۲. تنظیم شبکه LAN با فرمت مورد نظر تو (192.168.50.1/24)
uci set network.lan.device='eth0.20'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.50.1/24'
uci commit network

# ۳. تنظیم WAN
uci set network.wan=interface
uci set network.wan.device='eth0.10'
uci set network.wan.proto='pppoe'
uci set network.wan.username='fholde5973501@tct4'
uci set network.wan.password='54653397'
uci commit network

# ۴. گسترش هارد
if [ -b /dev/sda2 ]; then parted -s /dev/sda resizepart 2 100%; resize2fs /dev/sda2; fi

exit 0
