#!/bin/sh

# ۱. تنظیمات VLANها (eth0.10, eth0.20, eth0.30)
uci -q delete network.vlan10; uci -q delete network.vlan20; uci -q delete network.vlan30
uci set network.vlan10=device; uci set network.vlan10.type='8021q'; uci set network.vlan10.ifname='eth0'; uci set network.vlan10.vid='10'
uci set network.vlan20=device; uci set network.vlan20.type='8021q'; uci set network.vlan20.ifname='eth0'; uci set network.vlan20.vid='20'
uci set network.vlan30=device; uci set network.vlan30.type='8021q'; uci set network.vlan30.ifname='eth0'; uci set network.vlan30.vid='30'

# تنظیمات اصلی شبکه
uci set network.lan.device='eth0.20'; uci set network.lan.proto='static'; uci set network.lan.ipaddr='192.168.50.1'; uci set network.lan.netmask='255.255.255.0'
uci set network.wan=interface; uci set network.wan.device='eth0.10'; uci set network.wan.proto='pppoe'; uci set network.wan.username='fholde5973501@tct4'; uci set network.wan.password='54653397'
uci commit network

# ۲. رول تفکیک ترافیک ایران
uci delete passwall2.Iran 2>/dev/null
uci set passwall2.Iran='shunt_rules'; uci set passwall2.Iran.remarks='Iran'; uci add_list passwall2.Iran.domain_list='geosite:category-ir'; uci add_list passwall2.Iran.domain_list='ext:iran.dat:all'; uci set passwall2.Iran.ip_list='geoip:ir'; uci commit passwall2

# ۳. گسترش حافظه هارد
if [ -b /dev/sda2 ]; then parted -s /dev/sda resizepart 2 100%; resize2fs /dev/sda2; fi

exit 0
