name: Build Custom OpenWrt for HP t630

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Firmware
      run: |
        sudo apt-get update && sudo apt-get install -y zstd
        curl -L -k "https://downloads.openwrt.org/releases/25.12.4/targets/x86/64/openwrt-imagebuilder-25.12.4-x86-64.Linux-x86_64.tar.zst" -o ib.tar.zst
        tar --use-compress-program=zstd -xf ib.tar.zst
        cd openwrt-imagebuilder-25.12.4-x86-64.Linux-x86_64
        
        # تزریق مخازن جدید نسخه ۲۵.۱۲ (بسیار مهم)
        echo "src/gz passwall_packages https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-25.12/x86_64/passwall_packages" >> repositories.conf
        echo "src/gz passwall2 https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-25.12/x86_64/passwall2" >> repositories.conf
        
        # کامپایل ایمیج
        make image PROFILE="generic" PACKAGES="dnsmasq-full luci-app-passwall2 xray" FILES="../files"
