name: Build Custom OpenWrt for HP t630

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download OpenWrt Image Builder
      run: |
        wget https://downloads.openwrt.org/releases/25.12.4/targets/x86/64/openwrt-imagebuilder-25.12.4-x86-64.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-25.12.4-x86-64.Linux-x86_64.tar.xz
        mv openwrt-imagebuilder-25.12.4-x86-64.Linux-x86_64 imagebuilder

    - name: Copy Custom Files
      run: |
        cp -r files/ imagebuilder/
        chmod +x imagebuilder/files/etc/uci-defaults/99-custom-settings

    - name: Compile Firmware
      run: |
        cd imagebuilder
        make image PROFILE="generic" PACKAGES="dnsmasq-full -dnsmasq kmod-nft-tproxy kmod-nft-socket wget-ssl luci-app-passwall2 sing-box xray-core v2ray-geosite-ir parted resize2fs e2fsprogs fdisk" FILES="files"

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-HP-t630-Custom
        path: imagebuilder/bin/targets/x86/64/*combined-ext4.img.gz
